name: gadgetron
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=11.0
  - cython=0.29.21
  - gitpython=3.1.11
  - h5py=3.1.0
  - jupyter=1.0.0
  - matplotlib=3.1.3
  - numpy=1.19.2
  - pandas=1.1.3
  - pillow=8.0.1
  - pip=20.3
  - pydicom=2.1.0
  - python=3.8
  - pytorch=1.7.0
  - pyxb=1.2.6
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - setuptools=50.3.1
  - torchaudio=0.7.0
  - torchvision=0.8.1
  - pip:
      - git+https://github.com/ismrmrd/ismrmrd-python.git
      - git+https://github.com/ismrmrd/ismrmrd-python-tools.git
